'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class projectresults

    '''<summary>
    '''GrossTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrossTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ClaimCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClaimCount As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''NetTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''crtRecoveryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crtRecoveryStatus As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''crtProjectResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crtProjectResults As Global.System.Web.UI.DataVisualization.Charting.Chart
End Class
