'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''btnPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPdf As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''claimsummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents claimsummary1 As Global.OnlineStatus.claimsummary

    '''<summary>
    '''rootcauseanalysis1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rootcauseanalysis1 As Global.OnlineStatus.rootcauseanalysis

    '''<summary>
    '''rootcauseanalysisbyprocess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rootcauseanalysisbyprocess As Global.OnlineStatus.rootcauseanalysisbyprocess

    '''<summary>
    '''businessunitanalysis1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents businessunitanalysis1 As Global.OnlineStatus.businessunitanalysis

    '''<summary>
    '''currentitemsunder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currentitemsunder1 As Global.OnlineStatus.currentitemsunder

    '''<summary>
    '''trAudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAudit As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''auditprogress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents auditprogress1 As Global.OnlineStatus.auditprogress

    '''<summary>
    '''popClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popClaims As Global.DevExpress.Web.ASPxPopupControl
End Class
